language: cpp
os: linux

matrix:
  include:
    - compiler: gcc
      ## gcc doesn't like poco's #pragma GCC diagnostic
      env: CXXFLAGS="-Wno-pragmas"
    - compiler: clang
      ## activemq-cpp is a frequent offender for these, which fails the build due to log size
      env: CXXFLAGS="-Wno-overloaded-virtual -Wno-sign-conversion"

before_install:
  - sudo apt-get update -qq
  ## install worker dependencies
  - sudo apt-get install -y libassimp-dev libboost-all-dev libjansson-dev
  ## install active-mq cpp dependencies
  - sudo apt-get install -y uuid-dev libapr1-dev libssl-dev

install:
  - ./.travis/install-activemq-cpp.sh
  - ./.travis/install-poco-all.sh

script:
  - mkdir build && cd build && cmake ../
  - make
