language: cpp
os: linux

matrix:
  include:
    - compiler: gcc
      ## gcc doesn't like poco's #pragma GCC diagnostic
      env: CXXFLAGS="-Wno-pragmas"
    - compiler: clang
      ## activemq-cpp is a frequent offender for these, which fails the build due to log size
      env: CXXFLAGS="-Wno-overloaded-virtual -Wno-sign-conversion"

before_install:
  - sudo apt-get update -qq
  ## install worker dependencies
  - sudo apt-get install -y libassimp-dev libboost-all-dev libjansson-dev
  ## install active-mq cpp dependencies
  - sudo apt-get install -y uuid-dev libapr1-dev libssl-dev

install:
  ## build and install active-mq cpp
  - wget http://www.eu.apache.org/dist/activemq/activemq-cpp/3.8.4/activemq-cpp-library-3.8.4-src.tar.gz
  - tar -zxf activemq-cpp-library-3.8.4-src.tar.gz
  - cd activemq-cpp-library-3.8.4 && ./configure --prefix=/usr && make V=0 && sudo make install && cd ..
  ## build and install poco
  - wget http://pocoproject.org/releases/poco-1.6.0/poco-1.6.0-all.tar.gz
  - tar -xvf poco-1.6.0-all.tar.gz
  ## poco will always build with gcc on linux, therefore pass in the gcc cflags
  - cd poco-1.6.0-all && ./configure --cflags="-Wno-pragmas" --prefix=/usr --no-tests --no-samples --omit=Data/MySQL,Data/ODBC && make -s && sudo make install && cd ..

script:
  - mkdir build
  - cd build
  - cmake ../
  - make
