language: cpp

compiler:
  - gcc
  - clang

before_install:
  - sudo apt-get update -qq
  ## install worker dependencies
  - sudo apt-get install -y libassimp-dev libboost-dev libjansson-dev
  ## install active-mq cpp dependencies
  - sudo apt-get install -y uuid-dev libapr1-dev libssl-dev

install:
  ## build and install active-mq cpp
  - wget http://www.eu.apache.org/dist/activemq/activemq-cpp/3.8.4/activemq-cpp-library-3.8.4-src.tar.gz
  - tar -zxf activemq-cpp-library-3.8.4-src.tar.gz
  - cd activemq-cpp-library-3.8.4 && ./configure --prefix=/usr && make && make install && cd ..
  ## todo: poco
  - wget http://pocoproject.org/releases/poco-1.6.0/poco-1.6.0.tar.gz
  - tar -xvf poco-1.6.0.tar.gz
  - cd poco-1.6.0 && ./configure --prefix=/usr && make && make install && cd ..

os:
  - linux